-- OLYMPUS: All + Female Football + Female Cricket auctions
-- Preserves the existing franchise (formerly Male) auction as "All".
-- Female auctions are separate sessions with separate purse/player limits.
BEGIN;

-- ------------------------------------------------------------------
-- 1. Separate auction configs while keeping the existing first row
--    as the current All/franchise auction (so live/pending state stays intact).
-- ------------------------------------------------------------------
ALTER TABLE public.auction_config
  ADD COLUMN IF NOT EXISTS auction_type TEXT NOT NULL DEFAULT 'franchise';

-- The old auction system intentionally allowed only one config row.
-- We now have three independent auction sessions, so remove that
-- singleton restriction and instead enforce one config per auction_type.
DROP INDEX IF EXISTS public.auction_config_singleton_idx;

CREATE UNIQUE INDEX IF NOT EXISTS auction_config_auction_type_unique
  ON public.auction_config (auction_type);

UPDATE public.auction_config
SET auction_type = 'franchise'
WHERE id = (
  SELECT id FROM public.auction_config ORDER BY created_at, id LIMIT 1
);

INSERT INTO public.auction_config (
  total_budget, base_price, bid_increment, status, gender_mode, auction_type
)
VALUES
  (6000, 50, 50, 'setup', 'Female', 'female_football'),
  (6000, 50, 50, 'setup', 'Female', 'female_cricket')
ON CONFLICT (auction_type) DO UPDATE SET
  total_budget = EXCLUDED.total_budget,
  base_price = EXCLUDED.base_price,
  bid_increment = EXCLUDED.bid_increment,
  gender_mode = EXCLUDED.gender_mode;

-- ------------------------------------------------------------------
-- 2. A registration may participate in multiple independent auctions.
--    All uses auction_type=franchise for backward compatibility.
-- ------------------------------------------------------------------
ALTER TABLE public.auction_players
  DROP CONSTRAINT IF EXISTS auction_players_registration_unique;

ALTER TABLE public.auction_players
  DROP CONSTRAINT IF EXISTS auction_players_auction_type_check;

ALTER TABLE public.auction_players
  ADD CONSTRAINT auction_players_auction_type_check
  CHECK (auction_type IN ('franchise', 'girls_individual', 'female_football', 'female_cricket'));

CREATE UNIQUE INDEX IF NOT EXISTS auction_players_registration_type_unique
  ON public.auction_players (registration_id, auction_type);

-- ------------------------------------------------------------------
-- 3. Female-auction purse state. Only four franchises participate.
-- ------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.auction_franchise_budgets (
  auction_type TEXT NOT NULL CHECK (auction_type IN ('female_football', 'female_cricket')),
  franchise_id UUID NOT NULL REFERENCES public.franchises(id) ON DELETE CASCADE,
  total_budget INTEGER NOT NULL DEFAULT 6000 CHECK (total_budget >= 0),
  spent_amount INTEGER NOT NULL DEFAULT 0 CHECK (spent_amount >= 0),
  max_players INTEGER NOT NULL DEFAULT 11 CHECK (max_players > 0),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (auction_type, franchise_id),
  CHECK (spent_amount <= total_budget)
);

ALTER TABLE public.auction_franchise_budgets ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Authenticated users can view female auction budgets" ON public.auction_franchise_budgets;
CREATE POLICY "Authenticated users can view female auction budgets"
  ON public.auction_franchise_budgets FOR SELECT TO authenticated USING (TRUE);
REVOKE INSERT, UPDATE, DELETE ON public.auction_franchise_budgets FROM authenticated;
GRANT SELECT ON public.auction_franchise_budgets TO authenticated;
GRANT ALL ON public.auction_franchise_budgets TO service_role;

INSERT INTO public.auction_franchise_budgets (auction_type, franchise_id, total_budget, spent_amount, max_players)
SELECT t.auction_type, f.id, 6000, 0, 11
FROM (VALUES ('female_football'), ('female_cricket')) AS t(auction_type)
JOIN public.franchises f ON f.slug IN ('ocean-giants', 'shadow-fangs', 'phoenix-clan', 'fiery-falcons')
ON CONFLICT (auction_type, franchise_id) DO NOTHING;

-- Separate undo/redo stack for female auctions so All history is untouched.
CREATE TABLE IF NOT EXISTS public.female_auction_action_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  auction_type TEXT NOT NULL CHECK (auction_type IN ('female_football', 'female_cricket')),
  action_type TEXT NOT NULL CHECK (action_type IN ('bid', 'complete')),
  auction_player_id UUID NOT NULL REFERENCES public.auction_players(id) ON DELETE CASCADE,
  payload JSONB NOT NULL,
  is_undone BOOLEAN NOT NULL DEFAULT FALSE,
  created_by UUID DEFAULT auth.uid(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  undone_at TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS female_auction_history_stack_idx
  ON public.female_auction_action_history (auction_type, is_undone, id DESC);
ALTER TABLE public.female_auction_action_history ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Auction admins can view female action history" ON public.female_auction_action_history;
CREATE POLICY "Auction admins can view female action history"
  ON public.female_auction_action_history FOR SELECT TO authenticated
  USING (public.is_auction_admin());
REVOKE INSERT, UPDATE, DELETE ON public.female_auction_action_history FROM authenticated;
GRANT SELECT ON public.female_auction_action_history TO authenticated;
GRANT ALL ON public.female_auction_action_history TO service_role;

-- ------------------------------------------------------------------
-- Helpers
-- ------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.is_female_auction_type(p_auction_type TEXT)
RETURNS BOOLEAN LANGUAGE sql IMMUTABLE AS $$
  SELECT p_auction_type IN ('female_football', 'female_cricket');
$$;

CREATE OR REPLACE FUNCTION public.female_auction_sport_name(p_auction_type TEXT)
RETURNS TEXT LANGUAGE sql IMMUTABLE AS $$
  SELECT CASE p_auction_type
    WHEN 'female_football' THEN 'Football'
    WHEN 'female_cricket' THEN 'Cricket'
    ELSE NULL
  END;
$$;

CREATE OR REPLACE FUNCTION public.auction_scope_prepare(p_auction_type TEXT)
RETURNS INTEGER
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_sport TEXT;
  v_base INTEGER;
  v_inserted INTEGER;
BEGIN
  PERFORM public.auction_require_admin();
  IF NOT public.is_female_auction_type(p_auction_type) THEN
    RAISE EXCEPTION 'Unsupported female auction type: %', p_auction_type;
  END IF;
  v_sport := public.female_auction_sport_name(p_auction_type);
  SELECT base_price INTO v_base FROM public.auction_config WHERE auction_type = p_auction_type;

  WITH eligible AS (
    SELECT pr.id,
           row_number() OVER (ORDER BY pr.created_at, pr.roll_number, pr.id) - 1 AS q
    FROM public.player_registrations pr
    WHERE lower(trim(COALESCE(pr.gender, 'Male'))) = 'female'
      AND EXISTS (
        SELECT 1 FROM jsonb_array_elements(COALESCE(pr.sports, '[]'::jsonb)) s
        WHERE lower(trim(COALESCE(s->>'name',''))) = lower(v_sport)
      )
      AND NOT EXISTS (
        SELECT 1 FROM public.auction_players ap
        WHERE ap.registration_id = pr.id AND ap.auction_type = p_auction_type
      )
  )
  INSERT INTO public.auction_players (
    registration_id, base_price, status, queue_order, auction_type
  )
  SELECT id, v_base, 'upcoming', q, p_auction_type
  FROM eligible
  ON CONFLICT (registration_id, auction_type) DO NOTHING;

  GET DIAGNOSTICS v_inserted = ROW_COUNT;
  RETURN v_inserted;
END;
$$;

-- ------------------------------------------------------------------
-- Female scope state / start / pause-resume
-- ------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.auction_scope_start(p_auction_type TEXT)
RETURNS public.auction_config
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_config public.auction_config%ROWTYPE;
  v_current UUID;
BEGIN
  PERFORM public.auction_require_admin();
  IF NOT public.is_female_auction_type(p_auction_type) THEN
    RAISE EXCEPTION 'Unsupported female auction type';
  END IF;

  SELECT * INTO v_config FROM public.auction_config
  WHERE auction_type = p_auction_type FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Auction configuration missing'; END IF;
  IF v_config.status = 'live' THEN RAISE EXCEPTION 'The auction is already live'; END IF;

  IF v_config.status = 'paused' AND v_config.current_player_id IS NOT NULL THEN
    UPDATE public.auction_config SET status='live'
    WHERE id=v_config.id RETURNING * INTO v_config;
    RETURN v_config;
  END IF;

  SELECT id INTO v_current FROM public.auction_players
  WHERE auction_type=p_auction_type AND status='current'
  ORDER BY queue_order, created_at, id LIMIT 1 FOR UPDATE;

  IF v_current IS NULL THEN
    SELECT id INTO v_current FROM public.auction_players
    WHERE auction_type=p_auction_type AND status='upcoming'
    ORDER BY queue_order, created_at, id LIMIT 1 FOR UPDATE;
  END IF;

  IF v_current IS NULL THEN
    PERFORM public.auction_scope_prepare(p_auction_type);
    SELECT id INTO v_current FROM public.auction_players
    WHERE auction_type=p_auction_type AND status='upcoming'
    ORDER BY queue_order, created_at, id LIMIT 1 FOR UPDATE;
  END IF;

  IF v_current IS NULL THEN
    RAISE EXCEPTION 'No eligible female % players are available', public.female_auction_sport_name(p_auction_type);
  END IF;

  UPDATE public.auction_players SET status='current' WHERE id=v_current;
  UPDATE public.auction_config
  SET current_player_id=v_current, status='live'
  WHERE id=v_config.id RETURNING * INTO v_config;
  RETURN v_config;
END;
$$;

CREATE OR REPLACE FUNCTION public.auction_scope_toggle_live(p_auction_type TEXT)
RETURNS public.auction_config
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE v_config public.auction_config%ROWTYPE;
BEGIN
  PERFORM public.auction_require_admin();
  IF NOT public.is_female_auction_type(p_auction_type) THEN RAISE EXCEPTION 'Unsupported female auction type'; END IF;
  SELECT * INTO v_config FROM public.auction_config WHERE auction_type=p_auction_type FOR UPDATE;
  IF NOT FOUND OR v_config.current_player_id IS NULL THEN RAISE EXCEPTION 'There is no current player'; END IF;
  UPDATE public.auction_config
  SET status = CASE WHEN status='live' THEN 'paused' ELSE 'live' END
  WHERE id=v_config.id RETURNING * INTO v_config;
  RETURN v_config;
END;
$$;

-- ------------------------------------------------------------------
-- Female bidding. Same increment behavior as the current All auction:
-- first bid = base price; +50 below 500; +100 from 500 onward.
-- ------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.auction_scope_place_bid(p_auction_type TEXT, p_franchise_id UUID)
RETURNS public.auction_bids
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_config public.auction_config%ROWTYPE;
  v_player public.auction_players%ROWTYPE;
  v_budget public.auction_franchise_budgets%ROWTYPE;
  v_highest INTEGER;
  v_highest_fid UUID;
  v_amount INTEGER;
  v_count INTEGER;
  v_bid public.auction_bids%ROWTYPE;
BEGIN
  PERFORM public.auction_require_admin();
  IF NOT public.is_female_auction_type(p_auction_type) THEN RAISE EXCEPTION 'Unsupported female auction type'; END IF;

  SELECT * INTO v_config FROM public.auction_config
  WHERE auction_type=p_auction_type FOR UPDATE;
  IF NOT FOUND OR v_config.status <> 'live' OR v_config.current_player_id IS NULL THEN
    RAISE EXCEPTION 'There is no live player available for bidding';
  END IF;

  SELECT * INTO v_player FROM public.auction_players
  WHERE id=v_config.current_player_id AND auction_type=p_auction_type FOR UPDATE;
  IF NOT FOUND OR v_player.status <> 'current' THEN RAISE EXCEPTION 'Current player is unavailable'; END IF;

  SELECT * INTO v_budget FROM public.auction_franchise_budgets
  WHERE auction_type=p_auction_type AND franchise_id=p_franchise_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'This franchise does not participate in this female auction'; END IF;

  SELECT count(*) INTO v_count FROM public.auction_players
  WHERE auction_type=p_auction_type AND sold_to_franchise_id=p_franchise_id AND status='sold';
  IF v_count >= v_budget.max_players THEN RAISE EXCEPTION 'This franchise already has the maximum % players', v_budget.max_players; END IF;

  SELECT amount, franchise_id INTO v_highest, v_highest_fid
  FROM public.auction_bids WHERE auction_player_id=v_player.id
  ORDER BY amount DESC, created_at ASC, id ASC LIMIT 1;
  IF v_highest_fid = p_franchise_id THEN RAISE EXCEPTION 'This franchise is already the highest bidder'; END IF;

  v_amount := CASE WHEN v_highest IS NULL THEN v_player.base_price
                   WHEN v_highest < 500 THEN v_highest + 50
                   ELSE v_highest + 100 END;
  IF v_amount > v_budget.total_budget - v_budget.spent_amount THEN
    RAISE EXCEPTION 'This franchise has only % remaining in its purse', v_budget.total_budget-v_budget.spent_amount;
  END IF;

  DELETE FROM public.female_auction_action_history
  WHERE auction_type=p_auction_type AND is_undone=TRUE;

  INSERT INTO public.auction_bids (auction_player_id, franchise_id, amount)
  VALUES (v_player.id, p_franchise_id, v_amount) RETURNING * INTO v_bid;

  INSERT INTO public.female_auction_action_history (auction_type, action_type, auction_player_id, payload)
  VALUES (p_auction_type, 'bid', v_player.id,
    jsonb_build_object('bid_id',v_bid.id,'franchise_id',v_bid.franchise_id,'amount',v_bid.amount,'created_at',v_bid.created_at));
  RETURN v_bid;
END;
$$;

-- ------------------------------------------------------------------
-- Female sold / unsold. Does NOT write to global franchise_members;
-- these are separate sport-specific team auctions.
-- ------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.auction_scope_complete_current(p_auction_type TEXT, p_outcome TEXT)
RETURNS public.auction_config
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_config public.auction_config%ROWTYPE;
  v_player public.auction_players%ROWTYPE;
  v_bid public.auction_bids%ROWTYPE;
  v_next public.auction_players%ROWTYPE;
  v_count INTEGER;
  v_has_next BOOLEAN := FALSE;
BEGIN
  PERFORM public.auction_require_admin();
  IF NOT public.is_female_auction_type(p_auction_type) THEN RAISE EXCEPTION 'Unsupported female auction type'; END IF;
  IF p_outcome NOT IN ('sold','unsold') THEN RAISE EXCEPTION 'Outcome must be sold or unsold'; END IF;

  SELECT * INTO v_config FROM public.auction_config WHERE auction_type=p_auction_type FOR UPDATE;
  IF NOT FOUND OR v_config.current_player_id IS NULL THEN RAISE EXCEPTION 'There is no current player'; END IF;
  SELECT * INTO v_player FROM public.auction_players WHERE id=v_config.current_player_id FOR UPDATE;

  IF p_outcome='sold' THEN
    SELECT * INTO v_bid FROM public.auction_bids
    WHERE auction_player_id=v_player.id ORDER BY amount DESC, created_at ASC, id ASC LIMIT 1;
    IF NOT FOUND THEN RAISE EXCEPTION 'A player cannot be sold without a bid'; END IF;

    SELECT count(*) INTO v_count FROM public.auction_players
    WHERE auction_type=p_auction_type AND sold_to_franchise_id=v_bid.franchise_id AND status='sold';
    IF v_count >= (SELECT max_players FROM public.auction_franchise_budgets WHERE auction_type=p_auction_type AND franchise_id=v_bid.franchise_id) THEN
      RAISE EXCEPTION 'Winning franchise already has the maximum number of players';
    END IF;

    UPDATE public.auction_franchise_budgets
    SET spent_amount=spent_amount+v_bid.amount, updated_at=now()
    WHERE auction_type=p_auction_type AND franchise_id=v_bid.franchise_id
      AND spent_amount+v_bid.amount <= total_budget;
    IF NOT FOUND THEN RAISE EXCEPTION 'Winning franchise no longer has enough purse balance'; END IF;

    UPDATE public.auction_players SET status='sold', sold_to_franchise_id=v_bid.franchise_id,
      sold_price=v_bid.amount, sold_at=now() WHERE id=v_player.id;
  ELSE
    UPDATE public.auction_players SET status='unsold', sold_to_franchise_id=NULL,
      sold_price=NULL, sold_at=now() WHERE id=v_player.id;
  END IF;

  SELECT * INTO v_next FROM public.auction_players
  WHERE auction_type=p_auction_type AND status='upcoming'
  ORDER BY queue_order, created_at, id LIMIT 1 FOR UPDATE;
  v_has_next := FOUND;
  IF v_has_next THEN UPDATE public.auction_players SET status='current' WHERE id=v_next.id; END IF;

  DELETE FROM public.female_auction_action_history WHERE auction_type=p_auction_type AND is_undone=TRUE;
  INSERT INTO public.female_auction_action_history (auction_type, action_type, auction_player_id, payload)
  VALUES (p_auction_type, 'complete', v_player.id,
    jsonb_build_object(
      'outcome',p_outcome,
      'franchise_id',CASE WHEN p_outcome='sold' THEN v_bid.franchise_id ELSE NULL END,
      'winning_amount',CASE WHEN p_outcome='sold' THEN v_bid.amount ELSE NULL END,
      'next_player_id',CASE WHEN v_has_next THEN v_next.id ELSE NULL END,
      'config_status_before',v_config.status
    ));

  UPDATE public.auction_config
  SET current_player_id=CASE WHEN v_has_next THEN v_next.id ELSE NULL END,
      status=CASE WHEN v_has_next THEN 'live' ELSE 'completed' END
  WHERE id=v_config.id RETURNING * INTO v_config;
  RETURN v_config;
END;
$$;

CREATE OR REPLACE FUNCTION public.auction_scope_history_state(p_auction_type TEXT)
RETURNS TABLE (can_undo BOOLEAN, can_redo BOOLEAN)
LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
BEGIN
  PERFORM public.auction_require_admin();
  RETURN QUERY SELECT
    EXISTS(SELECT 1 FROM public.female_auction_action_history WHERE auction_type=p_auction_type AND is_undone=FALSE),
    EXISTS(SELECT 1 FROM public.female_auction_action_history WHERE auction_type=p_auction_type AND is_undone=TRUE);
END;
$$;

CREATE OR REPLACE FUNCTION public.auction_scope_undo_last(p_auction_type TEXT)
RETURNS JSONB
LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE
  a public.female_auction_action_history%ROWTYPE;
  v_next UUID;
  v_outcome TEXT;
  v_fid UUID;
  v_amount INTEGER;
BEGIN
  PERFORM public.auction_require_admin();
  SELECT * INTO a FROM public.female_auction_action_history
  WHERE auction_type=p_auction_type AND is_undone=FALSE ORDER BY id DESC LIMIT 1 FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Nothing to undo'; END IF;

  IF a.action_type='bid' THEN
    DELETE FROM public.auction_bids WHERE id=(a.payload->>'bid_id')::UUID;
  ELSE
    v_next := NULLIF(a.payload->>'next_player_id','')::UUID;
    v_outcome := a.payload->>'outcome';
    v_fid := NULLIF(a.payload->>'franchise_id','')::UUID;
    v_amount := COALESCE(NULLIF(a.payload->>'winning_amount','')::INTEGER,0);
    IF v_next IS NOT NULL THEN UPDATE public.auction_players SET status='upcoming' WHERE id=v_next; END IF;
    IF v_outcome='sold' THEN
      UPDATE public.auction_franchise_budgets SET spent_amount=GREATEST(0,spent_amount-v_amount),updated_at=now()
      WHERE auction_type=p_auction_type AND franchise_id=v_fid;
    END IF;
    UPDATE public.auction_players SET status='current', sold_to_franchise_id=NULL, sold_price=NULL, sold_at=NULL
    WHERE id=a.auction_player_id;
    UPDATE public.auction_config SET current_player_id=a.auction_player_id,status=COALESCE(a.payload->>'config_status_before','live')
    WHERE auction_type=p_auction_type;
  END IF;
  UPDATE public.female_auction_action_history SET is_undone=TRUE,undone_at=now() WHERE id=a.id;
  RETURN jsonb_build_object('undone',a.action_type,'id',a.id);
END;
$$;

CREATE OR REPLACE FUNCTION public.auction_scope_redo_last(p_auction_type TEXT)
RETURNS JSONB
LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE
  a public.female_auction_action_history%ROWTYPE;
  v_next UUID;
  v_outcome TEXT;
  v_fid UUID;
  v_amount INTEGER;
BEGIN
  PERFORM public.auction_require_admin();
  SELECT * INTO a FROM public.female_auction_action_history
  WHERE auction_type=p_auction_type AND is_undone=TRUE ORDER BY id ASC LIMIT 1 FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Nothing to redo'; END IF;

  IF a.action_type='bid' THEN
    INSERT INTO public.auction_bids (id,auction_player_id,franchise_id,amount,created_at)
    VALUES ((a.payload->>'bid_id')::UUID,a.auction_player_id,(a.payload->>'franchise_id')::UUID,
            (a.payload->>'amount')::INTEGER,(a.payload->>'created_at')::TIMESTAMPTZ)
    ON CONFLICT (id) DO NOTHING;
  ELSE
    v_next := NULLIF(a.payload->>'next_player_id','')::UUID;
    v_outcome := a.payload->>'outcome';
    v_fid := NULLIF(a.payload->>'franchise_id','')::UUID;
    v_amount := COALESCE(NULLIF(a.payload->>'winning_amount','')::INTEGER,0);
    IF v_outcome='sold' THEN
      UPDATE public.auction_franchise_budgets SET spent_amount=spent_amount+v_amount,updated_at=now()
      WHERE auction_type=p_auction_type AND franchise_id=v_fid AND spent_amount+v_amount<=total_budget;
      IF NOT FOUND THEN RAISE EXCEPTION 'Not enough purse to redo sale'; END IF;
      UPDATE public.auction_players SET status='sold',sold_to_franchise_id=v_fid,sold_price=v_amount,sold_at=now()
      WHERE id=a.auction_player_id;
    ELSE
      UPDATE public.auction_players SET status='unsold',sold_to_franchise_id=NULL,sold_price=NULL,sold_at=now()
      WHERE id=a.auction_player_id;
    END IF;
    IF v_next IS NOT NULL THEN
      UPDATE public.auction_players SET status='current' WHERE id=v_next;
      UPDATE public.auction_config SET current_player_id=v_next,status='live' WHERE auction_type=p_auction_type;
    ELSE
      UPDATE public.auction_config SET current_player_id=NULL,status='completed' WHERE auction_type=p_auction_type;
    END IF;
  END IF;
  UPDATE public.female_auction_action_history SET is_undone=FALSE,undone_at=NULL WHERE id=a.id;
  RETURN jsonb_build_object('redone',a.action_type,'id',a.id);
END;
$$;

-- ------------------------------------------------------------------
-- All auction
-- ------------------------------------------------------------------
-- IMPORTANT:
-- The existing curated All/franchise auction engine is intentionally
-- left unchanged. This preserves the current pending queue, completed
-- results, purse calculations, undo/redo behavior, and manual slot flow.
-- The application renames the existing Male auction to "All".
--
-- Female registrations remain eligible for All whenever they are
-- explicitly loaded into the existing curated All auction flow.
-- ------------------------------------------------------------------

-- Grants
GRANT EXECUTE ON FUNCTION public.auction_scope_prepare(TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.auction_scope_start(TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.auction_scope_toggle_live(TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.auction_scope_place_bid(TEXT,UUID) TO authenticated;
GRANT EXECUTE ON FUNCTION public.auction_scope_complete_current(TEXT,TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.auction_scope_history_state(TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.auction_scope_undo_last(TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.auction_scope_redo_last(TEXT) TO authenticated;

COMMIT;
